luster_shop/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include("profile.urls")),
    path('accounts/', include("allauth.urls")),
    path('', include("product.urls")),
]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

product/urls.py
from django.urls import path
from . import views


app_name = 'product'

urlpatterns = [
    # item list
    path('', views.ItemListView.as_view(), name='list'),

    # item detail
    path('product/<slug>/', views.ItemDetailView.as_view(), name='detail'),

    # add item to cart
    path('add-to-cart/<slug>/', views.add_to_cart, name='add_to_cart'),

    # order summary
    path('cart/', views.CartView.as_view(), name='cart'),
]

profile/urls.py
from django.urls import path
from . import views


app_name = 'profile'

urlpatterns = [
    path('signup/', views.signup, name='signup'),
    path('login/', views.signin, name='login'),
    path('logout/', views.signout, name='logout'),
]

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta http-equiv="x-ua-compatible" content="ie=edge">

  <title>{% block head_title %}eCommerce{% endblock %}</title>
  {% block extra_head %}
  {% endblock %}

  <!-- Font Awesome -->
  <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.11.2/css/all.css">
  <!-- Bootstrap core CSS -->
  <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
  <!-- Material Design Bootstrap -->
  <link href="{% static 'css/mdb.min.css' %}" rel="stylesheet">
  <!-- Your custom styles (optional) -->
  <link href="{% static 'css/style.min.css' %}" rel="stylesheet">

  <style type="text/css">
    html,
    body,
    header,
    .carousel {
      height: 60vh;
    }

    @media (max-width: 740px) {
      html,
      body,
      header,
      .carousel {
        height: 100vh;
      }
    }

    @media (min-width: 800px) and (max-width: 850px) {
      html,
      body,
      header,
      .carousel {
        height: 100vh;
      }
    }
  </style>
</head>

<body>

  {% include "navbar_main.html" %}

  <!--Main layout-->
  <main>
    <div class="container mt-5 pt-4">
      {% if messages %}
        <div>
          {% for message in messages %}
            <div class="alert alert-{{ message.tags }} alert-dismissible fade show" role="alert">
              {{ message }}
              <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                <span aria-hidden="true">&times;</span>
              </button>
            </div>
          {% endfor %}
        </div>
      {% endif %}

      {% block content %}
      {% endblock content %}

      {% block extra_body %}
      {% endblock extra_body %}

    </div>
  </main>
  <!--Main layout-->

  {% include "footer.html" %}

  <!-- SCRIPTS -->
  <!-- JQuery -->
  <script type="text/javascript" src="{% static 'js/jquery-3.4.1.min.js' %}"></script>
  <!-- Bootstrap tooltips -->
  <script type="text/javascript" src="{% static 'js/popper.min.js' %}"></script>
  <!-- Bootstrap core JavaScript -->
  <script type="text/javascript" src="{% static 'js/bootstrap.min.js' %}"></script>
  <!-- MDB core JavaScript -->
  <script type="text/javascript" src="{% static 'js/mdb.min.js' %}"></script>
  <!-- Initializations -->
  <script type="text/javascript">
    // Animations initialization
    new WOW().init();
  </script>

  {% block extra_scripts %}
  {% endblock extra_scripts %}
    
</body>
</html>

templates/footer.html
<!--Footer-->
<footer class="page-footer text-center font-small mt-4 wow fadeIn">

  <hr class="my-4">

  <!-- Social icons -->
  <div class="pb-4">
    <a href="https://www.facebook.com/mdbootstrap" target="_blank">
      <i class="fab fa-facebook-f mr-3"></i>
    </a>

    <a href="https://twitter.com/MDBootstrap" target="_blank">
      <i class="fab fa-twitter mr-3"></i>
    </a>

    <a href="https://www.youtube.com/watch?v=7MUISDJ5ZZ4" target="_blank">
      <i class="fab fa-youtube mr-3"></i>
    </a>

    <a href="https://plus.google.com/u/0/b/107863090883699620484" target="_blank">
      <i class="fab fa-google-plus-g mr-3"></i>
    </a>

    <a href="https://dribbble.com/mdbootstrap" target="_blank">
      <i class="fab fa-dribbble mr-3"></i>
    </a>

    <a href="https://pinterest.com/mdbootstrap" target="_blank">
      <i class="fab fa-pinterest mr-3"></i>
    </a>

    <a href="https://github.com/mdbootstrap/bootstrap-material-design" target="_blank">
      <i class="fab fa-github mr-3"></i>
    </a>

    <a href="http://codepen.io/mdbootstrap/" target="_blank">
      <i class="fab fa-codepen mr-3"></i>
    </a>
  </div>
  <!-- Social icons -->

  <!--Copyright-->
  <div class="footer-copyright py-3">
    © 2019 Copyright:
    <a href="https://mdbootstrap.com/education/bootstrap/" target="_blank"> MDBootstrap.com </a>
  </div>
  <!--/.Copyright-->

</footer>
<!--/.Footer-->

templates/navbar_main.html
{% load cart_template_tags %}
<!-- Navbar -->
<nav class="navbar fixed-top navbar-expand-lg navbar-light white scrolling-navbar mb-5">
  <div class="container">

    <!-- Brand -->
    <a class="navbar-brand waves-effect" href="{% url 'product:list' %}">
      <strong class="blue-text">فروشگاه لوستر</strong>
    </a>

    <!-- Collapse -->
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
      aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <!-- Links -->
    <div class="collapse navbar-collapse" id="navbarSupportedContent">

      <!-- Left -->
      <ul class="navbar-nav mr-auto">
      </ul>

      <!-- Right -->
      <ul class="navbar-nav">
        {% if request.user.is_authenticated %}
          <li class="nav-item ml-auto">
            <a class="nav-link waves-effect" href="{% url 'product:cart' %}">
              <sub class="badge red">{{ request.user | cart_item_count }}</sub>
              <i class="fas fa-shopping-cart"></i>
            </a>
          </li>
          <li class="nav-item ml-auto">
            <a href="{% url 'profile:logout' %}" class="nav-link waves-effect"
              <span class="clearfix d-sm-inline-block"> خروج </span>
            </a>
          </li>
        {% else %}
          <li class="nav-item ml-auto">
            <a href="{% url 'account_login' %}" class="nav-link waves-effect">
              <span class="clearfix d-sm-inline-block"> ورود </span>
            </a>
          </li>
          <li class="nav-item ml-auto">
            <a href="{% url 'account_signup' %}" class="nav-link waves-effect">
              <span class="clearfix d-sm-inline-block"> ثبت نام </span>
            </a>
          </li>
        {% endif %}
      </ul>
    </div>
  </div>
</nav>
<!-- Navbar -->